### ISSUE TITLE
Derives

### ISSUE THREAD

**Issue by TonalidadeHidrica** [rust-lang-ja/ac-library-rs#35]
What macros do we have to derive for structs?

**Comment by qryxip** [comment]
- [`Clone`](https://doc.rust-lang.org/1.42.0/std/clone/trait.Clone.html), [`Debug`](https://doc.rust-lang.org/1.42.0/std/fmt/trait.Debug.html)
    We should implement `Clone` and `Debug` for all of the types.
- [`Copy`](https://doc.rust-lang.org/1.42.0/std/marker/trait.Copy.html)
    If a type can implement `Copy` and is small enough, we should implement `Copy` for it.
    - [`clippy::trivially_copy_pass_by_ref`](https://rust-lang.github.io/rust-clippy/rust-1.42.0/#trivially_copy_pass_by_ref)
- [`Default`](https://doc.rust-lang.org/1.42.0/std/default/trait.Default.html)
    - [`clippy::new_without_default`](https://rust-lang.github.io/rust-clippy/rust-1.42.0/#new_without_default)
- [`Hash`](https://doc.rust-lang.org/1.42.0/std/hash/trait.Hash.html)
    We cannot insert into `Hash{Set, Map}` without `Hash` implementation.
- [`(Partial)Eq`](https://doc.rust-lang.org/1.42.0/std/cmp/trait.Eq.html)
    Required for `==`, `!=` operators.
- [`(Partial)Ord`](https://doc.rust-lang.org/1.42.0/std/cmp/trait.Ord.html)
    Required for comperation operators such as `<`, `<=`. Also types without `Ord` implementation cannot be store in `BTree{Set, Map}` or `BinaryHeap`.
- [`From`](https://doc.rust-lang.org/stable/std/convert/trait.From.html), [`Into`](https://doc.rust-lang.org/stable/std/convert/trait.Into.html), [`TryFrom`](https://doc.rust-lang.org/1.42.0/std/convert/trait.TryFrom.html), [`TryInto`](https://doc.rust-lang.org/1.42.0/std/convert/trait.TryInto.html) (**No derive macro in `std`**)
    With these implementations, we can easiliy convert types with `.into()`.
- [`FromStr`](https://doc.rust-lang.org/stable/std/str/trait.FromStr.html) (**No derive macro in `std`**)
    We can get values from stdin directly.
- [`Display`](https://doc.rust-lang.org/stable/std/fmt/trait.Display.html) (**No derive macro in `std`**)
    We can `println!` the values directly.
- [`FromIterator`](https://doc.rust-lang.org/1.42.0/std/iter/trait.FromIterator.html) (**No derive macro in `std`**)
    Collection-like types should be implement this, as we can construct them with `elements.collect::<Foo>()`.
- [`IntoIterator`](https://doc.rust-lang.org/1.42.0/std/iter/trait.IntoIterator.html) (**No derive macro in `std`**)
    Collection-like types should be implement this, as we can iterate elements with `for elem in &foo { .. }` or `for elem in foo { .. }`.
- `As{Ref, Mut}`, `Index{Mut}`, binary operators, ... (**No derive macro in `std`**)

**Comment by TonalidadeHidrica** [comment]
Thanks a lot.  I'll consider implementing those traits.
Should I close it now?

**Comment by qryxip** [comment]
Yes. We may discuss such a general topic in rust-jp.slack.com.

**Comment by qryxip** [comment]
We should discuss in each PR.
