### ISSUE TITLE
Rename the package name and/or the crate name

### ISSUE THREAD

**Issue by qryxip** [rust-lang-ja/ac-library-rs#47]
In Rust, it is common to set a repository name to `foo-rs` and to set a `package.name` to `foo`.

In actual, `cargo new` strip the `"-rs"` suffixes [until recently](https://github.com/rust-lang/cargo/pull/5013).

```console
$ cargo +1.15.1 new foo-rs --lib
note: package will be named `foo`; use --name to override
     Created library `foo-rs` project
```

Why don't we rename the package name to `ac-library` or `ac_library`?

**Comment by qryxip** [comment]
Or, or rather and, We can rename the `lib.name` to `"atcoder"` or something.

```toml
[lib]
name = "atcoder"
```

Then we can write in this way **in examples and integration-tests (if we will write them)** .

```rust
use atcoder::Dsu;
```

**Comment by koba-e964** [comment]
Agreed on `ac_library`. I'm afraid that `atcoder` may give a wrong impression that this crate is officially maintained by AtCoder, which is not quite right.

**Comment by TonalidadeHidrica** [comment]
I agree with this suggestion.  Do you think we shuold/can change this until 2023/04/07 (deadline of the language update?)

**Comment by qryxip** [comment]
I think we should do. Or rather, this is the last chance.

**Comment by qryxip** [comment]
I came up with another name. `acl`.

```rust
use acl::FenwickTree;
```

Repository name: `ac-library-rs`
`package.name`: `ac-library-rs`
`lib.name` (a.k.a. "crate_name"): `ac_library_rs` → `acl`

**Comment by TonalidadeHidrica** [comment]
Which name is used in crates.io ?   `package.name` or `lib.name`?   Also I'm not in favor of such a short name because it is not very descriptive.

**Comment by qryxip** [comment]
`package.name`.

Example: The default `crate_name` of [xml-rs](https://crates.io/crates/xml-rs) is `xml`.

**Comment by qryxip** [comment]
@manta1130 @kenkoooo @tttanikawa @hotman78 Mentioning to you as contributors. Would you give us your thoughts?

We have the following choices.

1. As is

    `package.name`: `ac-library-rs`
    `lib.name`: `ac_library_rs`

2. `ac-library`/`ac_library`

    `package.name`: **`ac-library`**
    `lib.name`: **`ac_library`**

3. `ac-library-rs`/`ac_library`

    `package.name`: `ac-library-rs`
    `lib.name`: **`ac_library`**

4. `atcoder` (same as the original ACL)

    `package.name`: `ac-library-rs`
    `lib.name`: **`atcoder`**

5. `acl`

    `package.name`: `ac-library-rs`
    `lib.name`: **`acl`**

**Comment by qryxip** [comment]
I created two PRs for 5. and 3.

@mizar Could you choose one and merge it? As I mentioned, today is the last chance.
