### ISSUE TITLE
In the crt, the constraint should be "1 <= m[i]", but the assert is "1 < m[i]"

### ISSUE THREAD

**Issue by manukeno** [rust-lang-ja/ac-library-rs#59]
ac-library-rs
https://github.com/rust-lang-ja/ac-library-rs/blob/ee0d3df1aa0e7d3c65daaa7cc9d7fb13a46928f2/src/math.rs#L36

original ACL
https://atcoder.github.io/ac-library/document_en/math.html
https://github.com/atcoder/ac-library/blob/2a8bc7147f23a8783d7c0603330773117fde710e/atcoder/math.hpp#L40

**Comment by manta1130** [comment]
Thank you for pointing it out.
